config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'dashboard#index'
  get 'dashboard/index'
  get 'dashboard/conference_events'

  devise_for :users
  resources :conference_rooms do
    member do
      get :book_room
      post :booked_room
      get :cancle_booking
    end
    collection do
      get :rooms_booked_by_user
    end
  end
  resources :holidays
end

app/models/holiday.rb
class Holiday < ApplicationRecord
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController

  before_action :set_holiday, only: [:show, :edit, :update, :destroy]

  def index
    @holidays = Holiday.page(params[:page]).per(8)
  end

  def new
    @holiday = Holiday.new
  end

 def create
  @holiday = Holiday.new(holiday_params)
    respond_to do |format|
      if @holiday.save
        format.html { redirect_to @holiday, notice: 'Holiday was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @holiday.update(holiday_params)
        format.html { redirect_to @conference_room, notice: 'Holiday was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @holiday.destroy
    respond_to do |format|
      format.html { redirect_to conference_rooms_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_holiday
      @holiday = Holiday.find(params[:id])
    end

    def holiday_params
      params.require(:holiday).permit(:name, :description, :day)
    end
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/_form.html.erb
<%= form_for(@holiday) do |f| %>
  <% if @holiday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@holiday.errors.count, "error") %> prohibited this holiday from being saved:</h2>

      <ul>
      <% @holiday.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :day %><br>
    <%= f.date_field :day %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/holidays/edit.html.erb
<h1>Edit Holiday</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/holidays/index.html.erb
<%= link_to 'Add New Holidays', new_holiday_path, class: "btn btn-success" %>
<hr>
<div class="row">
  <div class="col-sm-12">
    <div class="row">
      <% @holidays.each do |holiday| %>
        <div class="col-md-3">
          <div class="well">
            <h4 class="text-danger"><span class="label text-success pull-right label-color"><%= holiday.name %></span> name </h4>
            <p class="text-danger"><span class="label text-success pull-right label-color"><%= holiday.description %></span> Description </p>
            <p class="text-danger"><span class="label text-success pull-right label-color"><%= holiday.day %></span> ON Day </p>
            <div class="links">
              <%= link_to 'Show', holiday, class: "text-danger" %>
              <%= link_to 'Edit', edit_holiday_path(holiday), class: "text-danger" %>
              <%= link_to 'Destroy', holiday_path(holiday), class: "text-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= paginate @holidays, :theme => 'twitter-bootstrap-3',:pagination_class => "pagination-sm" %>

app/views/holidays/new.html.erb
<h1>New Holiday</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/holidays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @holiday.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @holiday.description %>
</p>

<p>
  <strong>Day:</strong>
  <%= @holiday.day %>
</p>


<%= link_to 'Edit', edit_holiday_path(@holiday) %> |
<%= link_to 'Back', root_path %>