config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'dashboard#index'
  get 'dashboard/index'
  get 'dashboard/conference_events'

  devise_for :users
  resources :conference_rooms do
    member do
      get :book_room
      post :booked_room
      get :cancle_booking
    end
    collection do
      get :rooms_booked_by_user
    end
  end
  resources :holidays
end

app/models/conference_room.rb
class ConferenceRoom < ApplicationRecord
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :facility
  belongs_to :user

  def booked_rooms_records
    BookedRoom.where(conference_room_id: self.id)
  end

  def booked_time_slot start_time, end_time
    self.booked_rooms_records.where('(start_time, end_time) overlaps (timestamp :start_time, timestamp :end_time)',:start_time => start_time, :end_time => end_time)
  end
end

app/controllers/conference_rooms_controller.rb
class ConferenceRoomsController < ApplicationController

  before_action :set_conference_room, only: [:show, :edit, :update, :destroy, :book_room, :booked_room, :cancle_booking]
  before_action :set_start_time_end_time, only: [:booked_room]


  def new
    @conference_room = current_user.conference_rooms.new
  end

  def create
    @conference_room = current_user.conference_rooms.new(conference_room_params)
    if @conference_room.save
      redirect_to @conference_room, notice: 'Conference_room was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @conference_room.update(conference_room_params)
      redirect_to @conference_room, notice: 'Conference_room was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @conference_room.destroy
    redirect_to root_path
  end

  def book_room
    @book_room = current_user.booked_rooms.build(:conference_room_id => @conference_room.id)
  end

  def booked_room
    if @conference_room.booked_rooms_records.count >= @conference_room.available_booking
      building_rooms
      redirect_to root_path, alert: "booking closed your request is in wait queue" and return
    else
      if @conference_room.booked_time_slot(@start_time, @end_time).present?
        building_rooms
        redirect_to root_path, alert: 'Conference_room is already booked for given time-slot So your request is in wait queue' and return
      elsif Holiday.where(day: [@start_day,@end_day]).present?
        redirect_to root_path, alert: 'Sorry its a holiday' and return
      end
      book_room = current_user.booked_rooms.build(booked_room_params)
      if book_room.valid?
        book_room.status = 0
        book_room.conference_room_id = params[:id]
        book_room.save
        #RoomBookingJob.perform_later(@conference_room.id, current_user.id)
        redirect_to root_path, notice: 'Conference_room booked successfully' and return
      else
        render :book_room
      end
    end
  end

  def rooms_booked_by_user
    @user_booked_rooms = current_user.booked_conference_rooms.where(status: 0).page(params[:page]).per(8)
  end

  def cancle_booking
    booked_room = current_user.booked_rooms.find_by(id: params[:booked_room_id])
    records = @conference_room.booked_rooms_records.where('(start_time, end_time) overlaps (timestamp :start_time, timestamp :end_time)',:start_time => booked_room.start_time, :end_time => booked_room.end_time)
      booked_room.destroy
      #RoomCancelingJob.perform_later(@conference_room.id, current_user.id)
    if records.present?
      records.first.update_attributes(status: 0)
      redirect_to root_path, notice: "Booking cancle successfully"
    elsif @conference_room.booked_rooms_records.count >= @conference_room.available_booking
      @conference_room.booked_rooms_records.where(status: 2).first.update_attributes(status: 0)
      redirect_to root_path, notice: "Booking cancle successfully"
    else
      render :rooms_booked_by_user, errors: "Something went wrong!!!"
    end
  end

  def building_rooms
    book_room = current_user.booked_rooms.build(booked_room_params)
    book_room.status = 2
    book_room.conference_room_id = params[:id]
    book_room.save
  end

  private

    def set_conference_room
      @conference_room = ConferenceRoom.find(params[:id])
    end

    def conference_room_params
      params.require(:conference_room).permit(:title, :description, :available_booking, :tag_list)
    end

    def booked_room_params
      params.require(:booked_room).permit(:start_time, :end_time, :all_day, :purpose, :status, :conference_room_id)
    end

    def set_start_time_end_time
      @start_time = DateTime.new(params[:booked_room]['start_time(1i)'].to_i, params[:booked_room]['start_time(2i)'].to_i, params[:booked_room]['start_time(3i)'].to_i,  params[:booked_room]['start_time(4i)'].to_i,  params[:booked_room]['start_time(5i)'].to_i)
      @end_time = DateTime.new(params[:booked_room]['end_time(1i)'].to_i, params[:booked_room]['end_time(2i)'].to_i, params[:booked_room]['end_time(3i)'].to_i,  params[:booked_room]['end_time(4i)'].to_i,  params[:booked_room]['end_time(5i)'].to_i)

      @start_day = DateTime.new(params[:booked_room]['start_time(1i)'].to_i, params[:booked_room]['start_time(2i)'].to_i, params[:booked_room]['start_time(3i)'].to_i)

      @end_day = DateTime.new(params[:booked_room]['end_time(1i)'].to_i, params[:booked_room]['end_time(2i)'].to_i, params[:booked_room]['end_time(3i)'].to_i)
    end
end

app/helpers/conference_rooms_helper.rb
module ConferenceRoomsHelper

  def remaining_availability conference_room
    count = conference_room.available_booking - conference_room.booked_rooms_records.count
    count1 = count <= 0 ? 0 : count
    return count1
  end

  def conference_room_data room
    @conference_room = ConferenceRoom.find_by(id: room.conference_room_id)
    @user = User.find_by(id: room.user_id)
  end

  def format_date(date_time)
   Time.at(date_time.to_i).to_formatted_s(:db)
  end
end

app/views/conference_rooms/_form.html.erb
<%= form_for(@conference_room) do |f| %>
  <% if @conference_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conference_room.errors.count, "error") %> prohibited this conference_room from being saved:</h2>

      <ul>
      <% @conference_room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :available_booking %><br>
    <%= f.number_field :available_booking %>
  </div>

  <div class="field">
    <%= f.label :all_tags %><br>
    <%= f.text_field :tag_list, placeholder: "Tags separated with comma" %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conference_rooms/book_room.html.erb
<%= form_for @book_room, url: booked_room_conference_room_path(@conference_room), method: :post do |f| %>

  <% if @book_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book_room.errors.count, "error") %> prohibited this book_room from being saved:</h2>

      <ul>
      <% @book_room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :purpose %><br>
    <%= f.text_field :purpose %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conference_rooms/edit.html.erb
<h1>Edit Conference Room</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/conference_rooms/new.html.erb
<h1>New Conference Room</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/conference_rooms/rooms_booked_by_user.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="row">
      <% @user_booked_rooms.each do |room| %>
      <% conference_room_data(room) %>
        <div class="col-md-3">
          <div class="well">
            <h4 class="text-success"><span class="label text-success pull-right label-color"><%= @conference_room.try(:title) %></span> Title </h4>
            <p class="text-success"><span class="label text-success pull-right label-color"><%= @conference_room.try(:description) %></span> Description </p>
            <p class="text-success"><span class="label text-success pull-right label-color"><%= format_date(room.start_time) %></span> Start Time </p>
            <p class="text-success"><span class="label text-success pull-right label-color"><%= format_date(room.end_time) %></span> End Time </p>
            <p class="text-success"><span class="label text-success pull-right label-color"><%= room.purpose %></span> Purpose </p>
            <p class="text-success"><span class="label text-success pull-right label-color"><%= room.status %></span> Status </p>
            <p class="text-success"><span class="label text-success pull-right label-color"><%= @user.name %></span> Booked By </p>
            <% if @user == current_user && @conference_room.present?%>
              <div class="links">
                <%= link_to 'Cancle booking', cancle_booking_conference_room_path(id: @conference_room.id, booked_room_id: room.id) %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= paginate @user_booked_rooms, :theme => 'twitter-bootstrap-3',:pagination_class => "pagination-sm" %>

app/views/conference_rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @conference_room.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @conference_room.description %>
</p>

<p>
  <strong>Available Booking:</strong>
  <%= @conference_room.available_booking %>
</p>

<p>
  <strong>Facility:</strong>
  <%= @conference_room.tag_list %>
</p>


<%= link_to 'Edit', edit_conference_room_path(@conference_room) %> |
<%= link_to 'Back', root_path %>